.gitignore, backend/package-lock.json, backend/package.json, backend/server.js
Fixes #2
Simple PR to setup node.js plus express and to initialize the backend directory.
=> feat(setup): setup basic express server and backend directory

backend/models/listing.js, backend/models/user.js
PR to set initial draft for `User` and `Listing` database schema. Changes to these schemas are sure to come. For now need an initial draft for these. Things to consider:
1. Will need to figure storage mechanism for multimedia files.
2. Will need to create schemas for chat related functionality between users.
References Issue #5
=> Starter Mongoose Schemas for MongoDB

.gitignore, backend/.env, backend/models/listing.js, backend/models/user.js, backend/package-lock.json, backend/package.json, backend/server.js, backend/simple_db_test/model.js, backend/simple_db_test/test_model.js
PR to set up mongodb connection working with mongo server running locally. A simple test has been added to verify if the connection works succesfully. Instructions on how to run the test will be provided below.
References Issue #3 
Test were setup under `backend/simple_db_test` and can be run through the commands below. First follow the steps on the next section to ensure you have installed MongoDB and it has been started as a service
```commandline
cd simple_db_test
node test_model.js
```
If successful you should see printed on the terminal:
```commandline
TESTING CONNECTION!!
TESTING INSERT
Connection successful! 
{
first_name: 'Denis',
last_name: 'Lalaj',
age: 23,
...
}
{
first_name: 'Matt',
last_name: 'Anderson',
age: 36,
...
}
```
If you have …
=> MongDB Setup and Simple Test

backend/src/app.js, backend/src/models/preferencesModel.js, backend/src/models/userModel.js, backend/src/routes/preferences.js, backend/src/routes/users.js, backend/src/tests/simple_db_test/test_model.js
Fixes #21 
- Create Preferences Schema
- Adds GET, POST, PUT for the Preferences module
1. Start dev server by `npm start`
2. Ensure you have created some users to be able to test any of the following routes out.
`GET /api/users/:userId/preferences ` gets the preferences for a user by ID
```bash
curl --request GET --header 'Content-Type: application/json' localhost:3000/api/users/<userID>/preferences
```
`POST /api/users/:userId/preferences` create preferences for a user by ID
```bash
curl --request POST --header 'Content-Type: application/json' --data '{"minPrice":800,"maxPrice":1600,"housingType":"studio","roommateCount":2,"petFriendly":"true","smoking":"no-smoking","partying":"neutral","drinking":"neutral","noise":"neutral","gender":"male","moveInDate":"2023-10-22","leaseLength":12, …
```
=> feat(Preferences) - Preferences Module Schema and REST Interfaces

backend/package-lock.json, backend/src/app.js, backend/src/models/listingModel.js, backend/src/models/preferencesModel.js, backend/src/models/userModel.js, backend/src/routes/listings.js, backend/src/routes/preferences.js, backend/src/routes/users.js
Fixes #23 
- Adds GET, POST, PUT, and DELETE endpoints to specific users
- Updates User schema
1. Start dev server by `npm start`
2. Try this workflow:
if using [httpie](https://httpie.io/)
```bash
http POST localhost:3000/api/users firstName=John lastName=Man email=testing@github.com gender=male birthday=2000-01-01 phoneNumber=1234567890 profilePicture=temp bio="Looking for housing!"
```
```bash
http localhost:3000/api/users/${{id_of_user}}
```
```bash
http PUT localhost:3000/api/users/${{id_of_user}} profilePicture=temp2 bio="This is my update bio!"
```
```bash
http DELETE localhost:3000/api/users/${{id_of_user}}
```
using cURL:
```bash
curl --request POST --header 'Content-Type: application/json' --data '{"firstName":"John","lastName":"Man","email":"testing@github.com"}' …
```
=> feat(users): user schema changes and REST endpoints

.github/pull_request_template.md, .github/workflows/backend-ci.yaml
=> chore(ci): simple backend gh ci

frontend/app/src/main/java/com/chads/vanroomies/ChatFragment.java, frontend/app/src/main/java/com/chads/vanroomies/Constants.java, frontend/app/src/main/java/com/chads/vanroomies/GetHelloWorldTest.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsRecyclerData.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsRecyclerViewAdapter.java, frontend/app/src/main/java/com/chads/vanroomies/ProfileFragment.java, frontend/app/src/main/res/layout/fragment_listings.xml
Fixes: #39
Integrates the frontend listings page with the backend. Currently, the page takes listing titles and the first image.
Due to limitations with .toString(), images larger than 8x8 (in base 64 format) are not accepted and will crash the app.
This will be looked into with issue #47.
2. Run `npm run dev`
3. Go to Postman and run `POST Create New User`
4. Take the outputted `_id` and run `POST Create Listing under User (With Image)` with the id as `userId`
5. Repeat step 4 as many times as you'd like
6. Take `_id` and paste it into `ListingsFragment` near the end of `onCreateView`. The userId is hardcoded at the moment. 
7. Build and run the app
8. The listings should show up in the listings menu!
=> feat(listings integration): Integrate Frontend Listings Fragment with Backend

frontend/app/src/main/java/com/chads/vanroomies/Constants.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsFragment.java, frontend/app/src/main/java/com/chads/vanroomies/SingleListingResponseResult.java, frontend/app/src/main/java/com/chads/vanroomies/ViewListingActivity.java, frontend/app/src/main/res/drawable/ic_edit.xml, frontend/app/src/main/res/layout/activity_view_listing.xml
Fixes: #55
Adds buttons to edit individual listings if the user is the owner/creator of the listing. If the user is not the owner, the edit buttons will be disabled and made invisible. Updates are sent to the backend via PUT requests.
2. Run `npm run dev`
3. Go to Postman and create a new user as well as some postings under that user.
4. Take the outputted userId and replace the hardcoded userId values with it.
5. Build and run the app
6. Go to a listing and see if you can edit!
7. These edits should immediately be seen and should persist when going from one listing to another.
Merge after:
https://github.com/FarihaIS/VanRoomies/pull/54
https://github.com/FarihaIS/VanRoomies/pull/53
https://github.com/FarihaIS/VanRoomies/pull/48
=> feat(edit listing): Add Editing Functionality to Individual Listings for Owners

frontend/app/build.gradle.kts, frontend/app/src/main/java/com/chads/vanroomies/Constants.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsFragment.java, frontend/app/src/main/res/layout/fragment_listings.xml, frontend/app/src/main/res/values/strings.xml
Fixes: #59
Adds a SwitchMaterial to toggle between Recommended and Owned listings. 
**Note:** Since the recommendation API is not on the BE in this PR, it calls the same API as owned. You can test by putting in a different userId for each of them, the two calls are distinct.
2. Run `npm run dev`
3. Go to Postman and run `POST Create New User`
4. Take the outputted `_id` and run `POST Create Listing under User (Without Image)` with the id as `userId`
5. Repeat step 4 as many times as you'd like
6. Take `_id` and paste it into `ListingsFragment` in the UserId String declared near the start of the class.
7. Create another user in Postman
8. Paste the '_id' in place of the reference to userId in either both calls of RecommendedListings or the call for OwnedListings
9. …
=> feat(toggle listing): Add Toggling Functionality for Owned and Recommended Listings

backend/src/models/listingModel.js, backend/src/models/preferencesModel.js
Related to: #77 
Fix schema for Preferences, no need for `required` field right now
N/A
=> fix(preferences): Schema fix for FE

frontend/app/src/main/java/com/chads/vanroomies/Constants.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ProfileFragment.java, frontend/app/src/main/java/com/chads/vanroomies/UserPreferencesResponseResult.java, frontend/app/src/main/res/layout/fragment_profile.xml, frontend/app/src/main/res/values/strings.xml
Fixes: #77 
- Add email and birthday to profile
- Add UserPreferences that are fetched, created, and updated in the Profile Page
- Add a button to handle creating/updating user preferences
- Information is validated before sending to the BE.
2. Run `npm run dev` inside the backend folder
3. Create a new user in Postman 
4. Build and run the app
5. In the ProfileFragment you should be able to add user preferences
6. Try this with valid and invalid inputs!
7. You can also edit the preferences in the same button (which should say "Edit" now)
8. Try this with valid and invalid inputs as well!
=> feat(create/modify preferences): Add a User Preferences to the Profile and Adding/Modifying Functions

frontend/app/src/main/java/com/chads/vanroomies/Constants.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsRecyclerViewAdapter.java, frontend/app/src/main/java/com/chads/vanroomies/MainActivity.java, frontend/app/src/main/java/com/chads/vanroomies/ProfileFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ViewListingActivity.java
Fixes: #47 
Fixes: #61
Integration with token authentication (disabled for M4), tracking of userId using SharedPreferences, and fixes the image size issue. 
2. Ensure your Google account is not already registered in your local DB
3. Uninstall and Reinstall the app (to force a new sign-in)
4. Log-in
5. Fill out your user preferences (they should be validated by the hints in the form)
6. Try editing your preferences (Existing values should be pre-filled)
7. Go to Listings and get recommended/owned listings
8. Create a new listing!
- The userId should be consistent through each step
- Trying to go to recommended listings before editing preferences should return an empty list
=> feat(login token + userId) Integrate Login Token Authentication, Track UserId, and Fix Image Size

frontend/app/src/main/java/com/chads/vanroomies/ChatChannelActivity.java, frontend/app/src/main/java/com/chads/vanroomies/ChatFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ChatListAdapter.java, frontend/app/src/main/java/com/chads/vanroomies/Constants.java, frontend/app/src/main/java/com/chads/vanroomies/MatchDeckAdapter.java, frontend/app/src/main/java/com/chads/vanroomies/MatchesFragment.java, frontend/app/src/main/java/com/chads/vanroomies/UserProfile.java
Fixes: #74 
*This change allows a user to receive new messages while they are currently viewing the conversation with the other user. It does so by adding a listener that waits on a "private message" event. This PR also fixes a minor bug that was present in Matches Fragment where the image of the match deck card was not set correctly and caused the app to crash.*
2. Run npm run dev inside the backend folder (ensure you have the required .env.development file as discussed in Discord)
3. Build and run the app on two emulators
4. Set preferences for both user as you like.
5. Go to the matches page of one user and swipe right on the other user you have created.
6. Go to the chat page and open the chat with that user.
7. On the second emulator, open this same chat.
8. Send …
=> enhancement(chatSocket) Debugging ChatSocket Functionality

frontend/app/src/main/java/com/chads/vanroomies/MainActivity.java
Fixes: #86 
This change fixes the "null null" name displayed on the ProfileFragment after initial account creation.
2. Delete your user from MongoDB
3. Launch the app and create a new account (Google Sign-In)
4. Your name should be immediately available on the login page!
=> enhancement(login bugfix) New Account Null Name Bugfix

backend/.gitignore, backend/package-lock.json, backend/package.json, backend/src/app.js, backend/src/chat/firebase.js, backend/src/chat/messageStore.js, backend/src/models/userModel.js
Fixes: #85
This change adds real time notifications to chat messaging.
2. etc...
=> feat(be-messaging): setup firebase real-time messaging on backend 

frontend/app/src/main/java/com/chads/vanroomies/ChatChannelActivity.java, frontend/app/src/main/java/com/chads/vanroomies/ChatChannelAdapter.java, frontend/app/src/main/java/com/chads/vanroomies/ChatFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ChatListAdapter.java, frontend/app/src/main/java/com/chads/vanroomies/Constants.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsRecyclerViewAdapter.java, frontend/app/src/main/java/com/chads/vanroomies/MainActivity.java, frontend/app/src/main/java/com/chads/vanroomies/MatchDeckAdapter.java, frontend/app/src/main/java/com/chads/vanroomies/MatchesFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ProfileFragment.java, frontend/app/src/main/java/com/chads/vanroomies/SingleListingResponseResult.java, frontend/app/src/main/java/com/chads/vanroomies/ViewListingActivity.java
Works toward fixing #93 
This change involves some fixes to some  issues (frontend only) identified by Codacy.
=> enhancement(codacy): FE fixes to some Codacy issues (Matches/Chat)

frontend/app/src/main/java/com/chads/vanroomies/ChatFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsRecyclerViewAdapter.java, frontend/app/src/main/java/com/chads/vanroomies/MatchesFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ProfileFragment.java, frontend/app/src/main/java/com/chads/vanroomies/UserPreferencesResponseResult.java, frontend/app/src/main/java/com/chads/vanroomies/ViewListingActivity.java
Works toward fixing: #93 
This pull request addresses some of the issues identified by Codacy for the Profile/Listings pages.
For testing, there should be no changes as most of the issues from Codacy are stylistic / removing unnecessary lines/checks.
=> enhancement(codacy): FE fixes to some Codacy issues (Profile/Listings)

backend/.gitignore, backend/package.json, backend/src/app.js, backend/src/authentication/jwtAuthentication.js, backend/src/chat/firebase.js, backend/src/chat/messageStore.js, backend/src/models/userModel.js, backend/src/routes/chat.js, backend/src/routes/listings.js, backend/src/routes/preferences.js, backend/src/routes/users.js, backend/src/sock.js, backend/src/utils/userRecommendations.js, myclient/client.js
Related: #91 
Fixes most codacy issues hopefully.
=> fix(codacy): fix various backend codacy issues

frontend/app/src/main/java/com/chads/vanroomies/ChatChannelActivity.java, frontend/app/src/main/java/com/chads/vanroomies/ChatChannelAdapter.java, frontend/app/src/main/java/com/chads/vanroomies/ChatFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ChatListAdapter.java, frontend/app/src/main/java/com/chads/vanroomies/Constants.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsRecyclerViewAdapter.java, frontend/app/src/main/java/com/chads/vanroomies/MainActivity.java, frontend/app/src/main/java/com/chads/vanroomies/MatchDeckAdapter.java, frontend/app/src/main/java/com/chads/vanroomies/MatchesFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ProfileFragment.java, frontend/app/src/main/java/com/chads/vanroomies/SingleListingResponseResult.java, frontend/app/src/main/java/com/chads/vanroomies/UserPreferencesResponseResult.java, frontend/app/src/main/java/com/chads/vanroomies/ViewListingActivity.java
=> fix(codacy): merge frontend codacy issues

backend/.gitignore, backend/package.json, backend/src/app.js, backend/src/authentication/jwtAuthentication.js, backend/src/chat/firebase.js, backend/src/chat/messageStore.js, backend/src/models/userModel.js, backend/src/routes/chat.js, backend/src/routes/listings.js, backend/src/routes/preferences.js, backend/src/routes/users.js, backend/src/sock.js, backend/src/utils/listingRecommendations.js, backend/src/utils/userRecommendations.js, myclient/client.js
=> fix(codacy): merge backend codacy fixes

backend/src/app.js, frontend/app/src/main/java/com/chads/vanroomies/MainActivity.java
*This change removes the deprecated function startActivityForResult inside MainActivity and resolves a minor bug in src/app.js where the path of cert.pem was configured incorrectly.*
=> Tested removal of deprecated startActivityForResult function

frontend/app/src/main/java/com/chads/vanroomies/Constants.java, frontend/app/src/main/java/com/chads/vanroomies/ViewListingActivity.java, frontend/app/src/main/res/layout/activity_view_listing.xml, frontend/app/src/main/res/values/strings.xml
Fixes: #107
Adds a "Report Scam" button to recommended listings in the ViewListing Activity
1. Start up MongoDB and run the server
2. Log in and set user preferences
3. Select a recommended listing. There should be a "Report Scam" button at the bottom of the screen
4. After reporting a listing, it should no longer be recommended
5. In "Owned Listings", listings should not have the report scam button.
=> feat(scam reporting): Add Scam Listing Reporting Button

backend/src/routes/users.js
Quickfix
Fix bug with "null" users for coming from blocking endpoint
N/A
=> bug(users): Quick fix for blocking

backend/src/authentication/googleAuthentication.js, backend/src/authentication/jwtAuthentication.js, backend/src/routes/listings.js, backend/src/routes/preferences.js, backend/src/routes/users.js, backend/src/utils/listingRecommendations.js, backend/src/utils/userRecommendations.js, backend/test/routes/listings.test.js, backend/test/routes/preferences.test.js, backend/test/routes/users.test.js
Fixes: #109 
Tests for listings and preferences as well as minor fixes on BE codebase
2. npm test
=> chore(be-tests): Denis Portion of Backend Jest Testing

backend/test/routes/users.test.js
=> fix(be-test): fix failing test

.github/workflows/jest-testing.yml
Fixes: #123 
Github Action for Regression Testing on push
=> ci(workflow): Jest testing Github Action

backend/src/routes/listings.js, backend/test/routes/listings.test.js
BE Fix
Minor fix - sort owned listings by creation date.
NA
=> fix(listings): Sort Listings by Creation Date

backend/src/routes/listings.js
=> fix(listings): Fix for Testing

frontend/app/build.gradle.kts, frontend/app/src/androidTest/java/com/chads/vanroomies/MainUsecaseTests.java, frontend/app/src/main/java/com/chads/vanroomies/Constants.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ViewListingActivity.java, frontend/app/src/main/res/layout/activity_view_listing.xml
Fixes: #114 
Fixes: #130 
Adds an Espresso test for:
- Creating a listing
- Modifying the listing
Adds a login helper in the MainUseCaseTests.java test suite to facilitate Google Sign-in during automated tests.
2. *Run the FE MainUseCaseTests.java test suite*
=> chore(fe-tests): Manage Listing Test + Login Helper

frontend/app/src/androidTest/java/com/chads/vanroomies/MainUsecaseTests.java
Fixes: #116 
Adds an Espresso test for:
- Chatting with a user
2. *Run the FE MainUseCaseTests.java test suite*
=> chore(fe-tests): Chat

frontend/app/src/androidTest/java/com/chads/vanroomies/MainUsecaseTests.java, frontend/app/src/androidTest/java/com/chads/vanroomies/NonFunctionalReqTests.java
Fixes: #133
Adds test cases for the non-functional requirements
- Get to any view in the app within 5 clicks
- Backend calls should return within 5 seconds
1. Start the server and MongoDB
2. Run NonFunctionalReqTests
=> chore(fe-tests): Non Functional Requirements Tests

frontend/app/src/androidTest/java/com/chads/vanroomies/NonFunctionalReqTests.java, frontend/app/src/main/java/com/chads/vanroomies/ChatChannelActivity.java
Updates the clicks test and fixes a chat user bug. Done in paired programming with the group.
=> bugfix(fe): Update Test and Fix Chat User Bug

backend/src/chat/firebase.js, backend/src/routes/chat.js, backend/test/routes/chat.test.js, backend/test/routes/listings.test.js, backend/test/sock.test.js, frontend/app/src/main/java/com/chads/vanroomies/ChatFragment.java, frontend/app/src/main/java/com/chads/vanroomies/Constants.java
=> fix(chat): fix chat order

frontend/app/src/androidTest/java/com/chads/vanroomies/NonFunctionalReqTests.java, frontend/app/src/main/java/com/chads/vanroomies/MatchesFragment.java, frontend/app/src/main/java/com/chads/vanroomies/ProfileFragment.java, frontend/app/src/main/java/com/chads/vanroomies/UserProfile.java
Fixes: #149 
*This change fixes a small bug in the matches fragment where the matches fragment was not being saved correctly.*
=> bugfix(matches) FE - Matches save state bugfix

frontend/app/src/androidTest/java/com/chads/vanroomies/MainUsecaseTests.java, frontend/app/src/androidTest/java/com/chads/vanroomies/NonFunctionalReqTests.java, frontend/app/src/main/java/com/chads/vanroomies/ListingsFragment.java, frontend/app/src/main/java/com/chads/vanroomies/MapsActivity.java, frontend/app/src/main/java/com/chads/vanroomies/ViewListingActivity.java, frontend/app/src/main/res/drawable/ic_delete.xml, frontend/app/src/main/res/layout/activity_view_listing.xml, frontend/app/src/main/res/values/strings.xml
- Rental Price is now shown in listings
- Rental Price can be edited within the listing (and will be validated before being sent to the BE)
- The default zoom for the map view has been increased to better capture the app's scope of Vancouver
- Added check for title length when editing listings
- Rewrote manageListingsTest to reflect the new changes and better line up with test specifications
1. Start MongoDB and the server
2. Run the test suite
3. Go to ListingsFragment
4. Create a new listing
5. Observe the rental price and try editing it. It should be numerical. Invalid values will cause a Toast message to pop up
6. Check the View Map button and note the default zoom
7. Try editing a listing title to a title with < 5 characters. A Toast message should pop up.
=> bugfix(listings) FE - Listings Bugfix Mega PR

.github/workflows/backend-code-style.yaml, backend/package.json
=> chore(linter): run github-actions lint check on every pull request that changes backend code

frontend/app/src/androidTest/java/com/chads/vanroomies/NonFunctionalReqTests.java
Changes a test case to reflect our non-functional requirement of 1 second load time.
=> fix(tests): non functional requirement fix
